services:

  svr:
    build:
      context: .
      args:
        - MOD=svr
    expose:
      - '8080'
    healthcheck:
      test: [ "CMD-SHELL", "nc -w 1 -z localhost 8080 || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  clt:
    build:
      context: .
      args:
        - MOD=clt
    depends_on:
      svr:
        condition: service_healthy
    environment:
      - SVR=svr
